name: 77Global Maven Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        project: [ delacruzex15, maven_project, maven_workflow ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Eclipse Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: ${{ matrix.project }}/pom.xml

      - name: Check Java version
        run: java -version

      - name: Build ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: mvn --batch-mode clean package